### ISSUE TITLE
Update README.MD to standardize workflow

### ISSUE THREAD

**Issue by adit-bala** [csmberkeley/csm-61a#112]
Workflow varies too much from the semester.

Will update README with, but not limited to:

- standard naming convention for branches, prs
- how to create folders, worksheets
- the thread will be updated as we go on

**Comment by gabeclasson** [comment]
Right now I'm thinking of making a style guide for worksheets and including information about the workflow in the readme (or perhaps a separate workflow doc?)

**Comment by adit-bala** [comment]
Resolving with #115
