### ISSUE TITLE
[fa22] mentor04 (Recursion)

### ISSUE THREAD

**Issue by adit-bala** [csmberkeley/csm-61a#133]
- make `Mandelbrot` one question with subparts
- add a new metaphor for recursion mini-lecture
- add alternation solutions for `factorial`, cut off at `n==1 or n== 0`

**Comment by gabeclasson** [comment]
- Last question (Mandelbrot) was a little long and confusing. (I have also personally heard this from many people, I agree that it should not be done in future semesters as the author of the problem, not matter how much I love it personally.)
