### ISSUE TITLE
[fa22] mentor05 (Tree Recursion)

### ISSUE THREAD

**Issue by gabeclasson** [csmberkeley/csm-61a#135]
- `make-change` (`make_change`): "one of my students is asking why we have find the minimum of using different coins, isn’t it always efficient to use the bigger coin" Add the following information to the meta:
    - this is tricky because unlike U.S. coins (and the coins of most countries) where the greedy algorithm of taking the largest coin each time is optimal, the specific values chosen for this problem complicate things significantly
    - I will make a note that this should be added to the meta in the future
    - an interesting problem for ppl in cs 70 is under what coin systems does the greedy algorithm work and under what conditions does it fail

**Comment by adit-bala** [comment]
- `donut question`: description is confusing and base cases are not clear
- `make-change`: a bit too open-ended, don't need all cases?
- `gibonacci`: making a base case of if it's less than or equal to 2 or if the input is 3

**Comment by gabeclasson** [comment]
Text overview/general stuff:
- Maybe include the is_leaf() function for tree selector on blurb (so far there is only branches() and label()).
- Would want more medium level questions, since gib was too easy, but mario number etch were too hard, big jump from gib to mario number
- Donut doesn't feel like a great placement, would prefer to do donuts after mario. Wasn't in comparison to the other problems.


`Mario-number`: 
- Mario was a little confusing to understand for the JMs, maybe would be nice to get some sort of visual to better understand it. The JMs liked the problem though, they just found it a little difficult to explain.
- everyone liked the mario problem. learned the most from this problem! 

`Donut`:  
- nobody liked the question 
- the base cases were confusing -> the problem didn't make sense in english
- Donut doesn't feel like a great placement, would prefer to do donuts after mario. Wasn't in comparison to the other problems.
- For the donut one, the description made no sense, JMs had to verbally explain it themselves to the students. The base case was confusing logically.
- The donut question was confusing for the students and was hard to explain for all JMs.
- Donut flavor question is confusing. 
- Would want more medium level questions, since gib was too easy, but mario number etch were too hard, big jump from gib to mario number

`has-sum`:
- liked Q5, the logic made sense in english

`discussions1`:
- good
