### ISSUE TITLE
61A Ideas

### ISSUE THREAD

**Issue by catherinecang** [csmberkeley/csm-61a#24]
From individual check ins! Just keeping them here for now

- I think the power outages have definitely had an effect on what I've able to cover, especially since I have a Monday section and makeup section times don't work for everyone. For future semesters, I think it would be helpful to have a large-group "catchup section" that students who had cancelled sections can attend for an overview of the material and a couple of selected problems from the worksheet. That way, the affected students can get at least a condensed view of the concepts covered and clear up any misconceptions/gaps in knowledge before moving onto dependent concepts later on.
- This is a bit specific to OOP stuff, but I really liked the intro section to CSM Worksheet 8. I think it would be super helpful if we could also include general guidelines (like 2 or 3 short steps) on how to draw OOP environment diagrams. It's an incredibly helpful tool and I feel like it could be emphasized just a bit more on that worksheet so students have some guidelines to look back at while attempting the questions or when going over the problems on their own later on.

Worksheet with apply-twice:
apply-twice is already in 61a discussion

**Comment by gabeclasson** [comment]
This feedback is a little bit idiosyncratic. OOP environment diagrams are not in scope. 

No longer relevant to current iteration of CSM 61A. Closed.
