### ISSUE TITLE
Fa20 Week 3

### ISSUE THREAD

**Issue by J4MIE1P** [csmberkeley/csm-61a#48]
Week 3 folder: https://drive.google.com/drive/folders/12Duj4pXyk5jvKMvZ0YVVAwjwFHBgQrXt?usp=sharing 

Feedback:
Didn’t finish but got through a good chunk
Students like that there was more content
Good to have lambda questions
In general: students don’t seem to understand the significance of lambdas
Add a motivation for lambdas to mini-lecture portion
More rev env diagrams

**Comment by gabeclasson** [comment]
The worksheet has changed to the extent that this issue is no longer relevant.
