### ISSUE TITLE
mentor09 doctests

### ISSUE THREAD

**Issue by LarynQi** [csmberkeley/csm-61a#66]
- [`delete_path_duplicates`](https://github.com/csmberkeley/csm-61a/blob/master/topics/trees/class/medium/delete-path-duplicates.tex) minor error in doctest when initializing `t2`. Should be `t2 = Tree(1, [Tree(2), Tree(2, [Tree(2, [Tree(1, [Tree(5)])])])])` I think
- Solution to [`skip`](https://github.com/csmberkeley/csm-61a/blob/master/topics/linked-lists/class/easy/skip.tex) without mutation is missing a colon in base case condition

**Comment by gabeclasson** [comment]
Someone [fixed](https://github.com/csmberkeley/csm-61a/commit/dcb22978c814968875c36fb25082e227e7757e4a) this a while ago and didn't close the issue.
